pages/api/create/user.ts
pages/api/get/users.ts
prisma/schema.prisma

created:
- endpoints get users
- create user
changed:
- schema.prisma dni bigInt to string

endpoint get users and create user

---

pages/api/read/professional/id/[id].ts
pages/api/read/professional/professional.ts
pages/api/read/professional/type/[type].ts

dynamic api routes professional id and type

dynamic api routes professional id and type

---

pages/api/create/user.ts
pages/api/read/professional/id/[id].ts
pages/api/update/user/[id].ts
prisma/schema.prisma

endopint
user-> age to birthday String
shchema
user-> age to birthday String

fixed schema

---

components/AdoptionsScreen.tsx
components/MainLayout.tsx
components/index.ts
styles/AdoptionsScreen.module.css

hice el componente de adoptions screen sin funcionalidad aun y pocos estilos

AdoptionsScreen component

---

components/LinkAdoption.tsx
styles/LinkAdoption.module.css

boton para ir a la página de adopcion

Link adoption

---

components/AdoptionCard.tsx
components/index.ts
next.config.js
pages/index.tsx
styles/AdoptionCard.module.css
styles/globals.css

- Adoption Card with their styles.
- globals.css set to light theme
- next.config.js support to remote images from unsplash and freepik

Adoptions card

---

components/AdoptionsComponent.tsx
styles/AdoptionsComponent.module.css

It is necessary to add styles to the 'select' tags, it is necessary to add functions that are executed in the onChange (To do 11/25/2022)

Adoption component

---

pages/api/create/adoptionpost.ts
pages/api/create/professional.ts
pages/api/read/adoptionposts/id/[id].ts

end Point error solve and new end Point get adoptions by id

end Point error solve

---

pages/api/create/adoptionpost.ts

cambios de tipo

---

components/AdoptionForm.tsx
next.config.js
utils/mediaUploader.ts

Se realiza modificacion en el form de adopciones para integrar cloudinary
Se creo una carpeta utils que contiene un archivo que permite cargar las imagenes
Se agrega el dominio res.cloudinary.com al archivo next.config.js

Ajuste cloudinary del form de adopciones

---

components/AdoptionCard.tsx
components/LinkAdoption.tsx
pages/api/create/adoptionpost.ts
pages/contact.tsx
styles/Contact.module.css
styles/LinkAdoption.module.css

Cambio tamaño botton

---

components/AdoptionDetails.tsx
components/LinkAdoption.tsx
package.json
styles/AdoptionDetails.module.css

Adoption details component, styles, package.json modified for supporting MUI and LinkAdoption modified

Adoption details

---

components/AdoptionCard.tsx
package.json
pages/_app.tsx
pages/adoptions/index.tsx
utils/dbFetching.ts

package.json modified, deleted redux dependencies

React query

---

app/types/index.ts
components/products/ProductCard.tsx
components/products/ProductOnCart.tsx
pages/products/index.tsx
pages/shoppingCart/index.tsx
styles/ShoppingCart.module.css

Se completa la funcionalidad del carrito de compras usando el local storage, los items agregados permanecen en el storage del navegador aunque se salga de la pagina o se recargue.
Faltaria integrar esto con la autenticacion para que se tenga el cuenta el id del usuario y asi guardar en localstorage los productos que cada usuario selecciona cuando va a hacer compras

shoppingcart

---

pages/api/read/filterOptions.ts

api/read/filterOptions
trae las opciones necesarias para llenar los filtros usando este formato {
size: string[];
breed: string[];
years: string[];
months: string[];
}

Create filter Options

---

app/types/index.ts
components/adoptions/AdoptionDetails.tsx
components/adoptions/AdoptionForm.tsx
pages/api/adoptionpost/index.ts
pages/products/index.tsx
utils/dbFetching.ts

Se actualiza el formulario de crear postadopt para que use react-query y tambien se cambia un poco la estructura agregando un campo para la descripcion de la mascota que sera opcional
Tambien se hacen unas modificaciones en el endpoint para crear el post en la base de datos

Actualizacion de form con react-query

---

components/products/payments/Checkout.tsx
components/products/payments/ModalPayment.tsx
package.json
pages/api/product/payment/index.ts
pages/shoppingCart/index.tsx
styles/ModalPayment.module.css

Package.json modified to bring stripe.
Added to API a new file, to make backend stripe's requests.
Added new folder in Products, TO RENDER===>>>> MODALPAYMENT.TSX

Payment checkout

---

pages/products/index.tsx

fixedSometroublesNotall

---

pages/shoppingCart/index.tsx
styles/ProductCard.module.css

Se soluciona el problema que se producia al recargar la pagina del carrito

solucion al error de localstorage

---

app/types/index.ts
components/layout/Filters.tsx
components/layout/Filtersproducts.tsx
components/products/ProductCard.tsx
pages/adoptions/index.tsx
pages/products/index.tsx
styles/Filters.module.css
utils/dbFetching.ts

fixed the pagination number on display

fixedPagination

---

components/layout/Filters.tsx
components/layout/Filtersproducts.tsx
utils/dbFetching.ts

filter adoptions combined fixed

fixedFilterFromAdoptions

---

components/products/payments/Checkout.tsx
components/products/payments/ModalPayment.tsx
package.json
utils/error.ts
utils/success.ts

added alerts in utils for failures and successes and added sweetalert to the json

change some things in the payment route

---

components/layout/Navbar.tsx
components/products/ProductCard.tsx
package.json
pages/_app.tsx
pages/api/auth/[...auth0].ts
pages/products/index.tsx
styles/ProductCard.module.css

added auth0 as authentication method and fixed some styles in product…

Auth0 and some style fixes

---

components/layout/Filters.tsx
components/layout/Filtersproducts.tsx

fixedFilter

---

app/types/index.ts
components/products/payments/Checkout.tsx
pages/api/sendMail/index.ts
utils/alerts.ts
utils/dbFetching.ts
utils/error.ts
utils/success.ts

el envio del email luego de la compra y debug de algunas cosas y cambie el utils de alerts

Payment email

---

components/products/ProductCard.tsx
components/products/ProductOnCart.tsx
pages/api/product/index.ts
pages/products/index.tsx
pages/shoppingCart/index.tsx

Solucion del bug para que quede vacio el carrito aun cuando se recarga la pagina.
Ajustes para que se tenga en cuenta el stock de cada item 
Notificacion de success cuando se agrega un articulo al carrito

bug en shopping cart

---

components/products/payments/Checkout.tsx
pages/contact/index.tsx
pages/products/index.tsx
utils/alerts.ts

cambios en el util alert y en la funcion addtocart

change alerts util and the addtocart function

---

components/layout/Filters.tsx
utils/dbFetching.ts

Hice los cambios al filtro de adopciones, pero también mantuve una copia del anterior para ver si les parece como quedó

filter+dbfetchingfunction

---

components/products/payments/Checkout.tsx
pages/api/sendMail/index.ts
pages/contact/index.tsx
utils/mailer.ts

cambie el formato del email de contacto y el de la factura

format email contact and checkIn

---

components/products/payments/Checkout.tsx

se hacen las transacciones cuando hay una compra y se actualiza el stock de productos tambien

add transactions and update stock

---

components/layout/Filters.tsx
components/layout/Filtersproducts.tsx

les puse un par de animaciones a los botones y terminé todo el tailwind de los filtros

actualizacion filters tailwind

---

components/layout/Filtersproducts.tsx
components/layout/Footer.tsx
components/layout/Navbar.tsx
pages/adoptions/index.tsx
pages/products/index.tsx
tailwind.config.js

cambiamos el navBar a responsive, lo mismo para el footer, agregamos algunas animaciones y botones

cambios en navBar responsive

---

components/products/ProductDetail.tsx
pages/adoptions/create/index.tsx
pages/adoptions/index.tsx
pages/products/[id].tsx
pages/products/index.tsx
pages/shoppingCart/index.tsx
utils/alerts.ts

El usuario sera redirigido a la pagina de autenticacion de auth0 cuando intente ingresar a las paginas del carrito de compras y el formulario para crear un post de adopcion
Tambien debera iniciar sesion para agregar productos al carrito

Protected paths

---

components/dashboard/tables/tools/formCreateUser.tsx
components/dashboard/tables/users/index.tsx
utils/dbFetching.ts

falta verificacion y acomdar tailwind para mandar coopiar pegar en transacciones adopciones y productos

faltaVerificacion

---

app/types/index.ts
components/dashboard/tables/transaction/index.tsx
pages/api/sendMail/index.ts
utils/dbFetching.ts

añadi el envio de correo al usuario cuando se cambia el estado de la transaccion

status transaction email

---

components/dashboard/tables/tools/createAdoptionForm.tsx
components/dashboard/tables/tools/formCreateProduct.tsx

modal implem

---

utils/createDB.ts

Se agregan productos y reviews al archivo CreateDB para que se puedan visualizar en la pagina

Agregar productos y reviews

---

components/adoptions/AdoptionDetails.tsx
components/layout/Filters.tsx
components/layout/Filtersproducts.tsx
components/products/ProductCard.tsx
pages/adoptions/index.tsx
pages/products/index.tsx

Cambios visuales

---

pages/products/[id].tsx

Se soluciona bug al selecionar los detalles de un producto relacionado

Actualizar detalles del producto

---

components/dashboard/dashboardUser/myTransaction/index.tsx

fix toggle collapse/expande
fix typescript error

fixed MyTransactionTable
